Repository laminas/laminas-serializer, pull requests merged in 2023-07, with the labels that each got.

#23 Apply formatter requirements to documentation
  README.md
Labels: Documentation, Enhancement

#22 Add extensions to CI requirements
  .laminas-ci.json
Labels: Enhancement

#25 Support and require `laminas-servicemanager` v4.0
  composer.json
  composer.lock
  src/AdapterPluginManager.php
  src/AdapterPluginManagerFactory.php
  src/Serializer.php
  test/AdapterPluginManagerCompatibilityTest.php
  test/AdapterPluginManagerFactoryTest.php
  test/SerializerTest.php
Labels: BC Break, Enhancement

#26 Rebirth of `laminas/laminas-serializer`
  .github/workflows/auto-close.yml
  README.md
Labels: Enhancement

#29 Enable renovate for serializer component
  renovate.json
Labels: Enhancement

#28 Deprecation of `MsgPack`, `PythonPickle` and `Wddx`
  src/Adapter/MsgPack.php
  src/Adapter/PythonPickle.php
  src/Adapter/PythonPickleOptions.php
  src/Adapter/Wddx.php
  src/Adapter/WddxOptions.php
Labels: Enhancement

#32 Remove superfluous whitespace in documentation
  README.md
Labels: Documentation

#27 Removal of niche serializer adapters
  .laminas-ci.json
  composer.json
  composer.lock
  docs/book/adapter.md
  src/Adapter/MsgPack.php
  src/Adapter/PythonPickle.php
  src/Adapter/PythonPickleOptions.php
  src/Adapter/Wddx.php
  src/Adapter/WddxOptions.php
  src/AdapterPluginManager.php
  test/Adapter/MsgPackTest.php
  test/Adapter/PythonPickleSerializeProtocol0Test.php
  test/Adapter/PythonPickleSerializeProtocol1Test.php
  test/Adapter/PythonPickleUnserializeTest.php
  test/Adapter/WddxTest.php
  test/AdapterPluginManagerCompatibilityTest.php
  test/SerializerTest.php
Labels: BC Break, Documentation, Enhancement

#36 Remove support for PHP 8.0, Upgrade PHPUnit to 10.x
  composer.json
  composer.lock
  phpcs.xml.dist
  phpunit.xml.dist
  src/Adapter/AbstractAdapter.php
  src/Adapter/AdapterInterface.php
  src/Adapter/AdapterOptions.php
  src/Adapter/IgBinary.php
  src/Adapter/Json.php
  src/Adapter/JsonOptions.php
  src/Adapter/PhpCode.php
  src/Adapter/PhpSerialize.php
  src/Adapter/PhpSerializeOptions.php
  src/AdapterPluginManager.php
  src/AdapterPluginManagerFactory.php
  src/ConfigProvider.php
  src/Exception/ExceptionInterface.php
  src/Exception/ExtensionNotLoadedException.php
  src/Exception/InvalidArgumentException.php
  src/Exception/RuntimeException.php
  src/Module.php
  src/Serializer.php
  test/Adapter/IgBinaryTest.php
  test/Adapter/JsonTest.php
  test/Adapter/PhpCodeTest.php
  test/Adapter/PhpSerializeTest.php
  test/AdapterPluginManagerCompatibilityTest.php
  test/AdapterPluginManagerFactoryTest.php
  test/SerializerTest.php
  test/TestAsset/Dummy.php
Labels: Enhancement
