Repository laminas/laminas-serializer, pull requests merged in 2023-09, with the labels that each got.

#40 Documentation and initial migration guide for 3.0.0
  docs/book/v2/adapter.md
  docs/book/v2/intro.md
  docs/book/v2/plugin-manager.md
  docs/book/v3/adapter.md
  docs/book/v3/intro.md
  docs/book/v3/migration/to-version-3.md
  docs/book/v3/plugin-manager.md
  mkdocs.yml
Labels: Documentation

#41 Deprecate `Laminas\Serializer\Serializer`
  src/ConfigProvider.php
  src/GenericSerializerFactory.php
  src/Serializer.php
  test/GenericSerializerFactoryTest.php
Labels: Enhancement

#43 Require stable v4.0 of `laminas-servicemanager`
  composer.json
  composer.lock
Labels: Enhancement

#44 Apply changes to `docs-build` workflow
  .github/workflows/docs-build.yml
Labels: Documentation

#46 Add missing `AdapterPluginManager` service to `ConfigProvider`
  composer.json
  composer.lock
  src/ConfigProvider.php
  test/ConfigProviderTest.php
Labels: Bug

#50 Updates workflow file for docs build to use DEPLOY_TOKEN
  .github/workflows/docs-build.yml
Labels: Bug, Documentation
